### PR TITLE
Run constrained for exclusion with jpeg

### LINKED ISSUE #24: Package collision with jpeg
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This package is colliding with @conda-forge/jpeg. Packages should be disjoint or use run constraints to prevent installation into the same environment.

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'bin/cjpeg'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'bin/djpeg'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'bin/jpegtran'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'bin/rdjpgcom'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'bin/wrjpgcom'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'include/jconfig.h'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'include/jerror.h'
```

### Installed packages

```shell
The following NEW packages will be INSTALLED:

    _libgcc_mutex:     0.1-conda_forge              conda-forge
    _openmp_mutex:     4.5-2_kmp_llvm               conda-forge
    attrs:             22.2.0-pyh71513ae_0          conda-forge
    biopython:         1.80-py38h0a891b7_0          conda-forge
    brotli:            1.0.9-h166bdaf_8             conda-forge
    brotli-bin:        1.0.9-h166bdaf_8             conda-forge
    bzip2:             1.0.8-h7f98852_4             conda-forge
    c-ares:            1.18.1-h7f98852_0            conda-forge
    ca-certificates:   2022.12.7-ha878542_0         conda-forge
    cached-property:   1.5.2-hd8ed1ab_1             conda-forge
    cached_property:   1.5.2-pyha770c72_1           conda-forge
    certifi:           2022.12.7-pyhd8ed1ab_0       conda-forge
    cftime:            1.6.2-py38h26c90d9_1         conda-forge
    colorama:          0.4.6-pyhd8ed1ab_0           conda-forge
    contourpy:         1.0.6-py38h43d8883_0         conda-forge
    cppe:              0.3.1-py38h2c0f9b2_9         conda-forge
    curl:              7.87.0-hdc1c0ab_0            conda-forge
```

### Environment info

```shell
This output was from a build on staged recipes.
```

### PR DESCRIPTION
**Pull request by hmaarrfk**
https://github.com/conda-forge/conda-forge.github.io/issues/673

Closes #24 (well when I merge the repo data patch, it will close it)
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by ocefpaf** [comment]
I believe that this one is probably the first one to be merged in the move jpeg->libjpeg-tubo. right?

**Comment by hmaarrfk** [comment]
Yes.  The jpeg maintainers already merged theirs. I have a standing PR to backfill the missing constraint too.

**Comment by hmaarrfk** [comment]
The list of all PRs is at the bottom of the cross referenced thread.

**Comment by ocefpaf** [comment]
Some PRs are waiting down the line. Let's merge this one.

**Pull request merged**
